name: MetaOCaml
on: [push, pull_request]
jobs:
  install:
    name: Install
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler: [ 'ocaml-variants.4.11.1+BER', 'ocaml-variants.4.14.1+BER' ]
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Deps
        run: |
          opam remote add metaocaml .
          opam install --yes ocamlfind
          opam install --yes `ls packages`
